### ISSUE TITLE
`err instanceof UniqueViolationError` not true when using mariadb

### ISSUE THREAD

**Issue by paulogdm** [Vincit/objection-db-errors#2]
Hello!
First, I'm a little new to this library and I do appreciate the ambition of this project.
I'm using objection + mariadb + knex adn I'm trying to catch a simple unique error, but it is not working as intended.
Example:
```
// Knex migration file
exports.up = function (knex, Promise) {
  return Promise.all([
    knex.schema.createTable('user', function (table) {
      table.increments('id').primary()
      table.string('name').nullable()
      table.string('email').notNullable()
      table.string('password', 64).notNullable()
    }),
    knex.schema.alterTable('user', function (table) {
      table.unique('email')
      table.unique('facebookid')
    })
  ])
}

exports.down = function (knex, Promise) {
  return Promise.all([
    knex.schema.dropTable('user')
  ])
}

// Function
const { Model } = require('objection')
const { UniqueViolationError } = require('objection-db-errors')
const Knex = require('knex')

  const knex = Knex({
    client: 'mariasql',
    connection: {
      host: '127.0.0.1',
      db: '',
      database: '',
      user: '',
      password: '',
      charset: 'utf8'
    },
    useNullAsDefault: true
  })

  // Initialize Model
  Model.knex(knex)

class BaseModel extends DbErrors(Model) {}

cont User = class User extends Model {
  static get tableName () {
    return 'User'.toLowerCase()
  }
}

try {
    const newuser = await User.query().insert({email: "unicorn@cornfield.com", password: "123456"})
    const newusernotunique = await User.query().insert({email: "unicorn@cornfield.com", password: "123456"})
} catch (err) {
    if (err instanceof UniqueViolationError) {
         // never prints
         console.info("Unique failed")
      } else {
       // outputs { code: 1062 }
      // Code 1062 in maria is a unique key violation
        console.info(err)
      }
}

```
Any help is welcome!

**Comment by koskimas** [comment]
User seems to be extending Model instead of BaseModel.

**Comment by paulogdm** [comment]
This is a snippet error. Im making a repo.
Ty in advance Koskimas!

**Comment by koskimas** [comment]
Damn, aren't mariadb and mysql supposed to be compatible? `db-errors` is not tested against mariadb, only mysql, sqlite and postgres. Apparently we need to test against mariadb too if we want to support it. I don't know if I want to do that yet. How popular is mariadb compared to mysql?

**Comment by paulogdm** [comment]
I could help you to support it in the future.
I have worked (a little, Im still a CS student...) with Oracle, Postgresql, MySql and Mariadb. The strongest argument to use maria today is about the support and development choices over MySQL. While MySQL is indeed closed source, each big step taken by maria is followed by discussions with the community. Many linux distros just accept mysql as mariadb today: If you do this in arch: `# pacman -S mysql` you are not installing mysql perse, but maria! Several changes applied by the MariaDB team addressed many issues with the good and old mysql, including performance problems that MySQL faces today...

**Comment by koskimas** [comment]
If the goal of mariadb is to be a drop-in replacement for mysql, it's even more weird that their error codes don't match.

**Comment by paulogdm** [comment]
A quick look at [MariaDB errors](https://mariadb.com/kb/en/library/mariadb-error-codes/) and [MySQL errors](https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html) is showing that they are indeed shared... Weird.

**Comment by koskimas** [comment]
@paulogdm I just learned that the mariasql driver hasn't been maintained in years and is pretty much useless.  You should use `mysql` driver which works perfectly with mariadb (mardiadb is a drop-in replacement for mysql).

**Comment by paulogdm** [comment]
Yep, I'm the same guy, now it works perfect. Sorry for the trouble.  🍺

**Comment by koskimas** [comment]
No problem. I posted the solution here too for others to find.
