### ISSUE TITLE
`ER_NO_DEFAULT_FOR_FIELD` is instance of `DBError` and not `NotNullViolationError`

### ISSUE THREAD

**Issue by tsm91** [Vincit/objection-db-errors#3]
Hi, i am not sure if this is a bug. I wanted to create a new record in user table without specifying the `first_name` value. Db thows `ER_NO_DEFAULT_FOR_FIELD`. I would expect that this plugin wraps this error into a `NotNullViolationError`. Instead of `DBError` instance

<img width="897" alt="screen shot 2018-07-15 at 12 23 43" src="https://user-images.githubusercontent.com/4459551/42732947-c4404258-882a-11e8-9a83-bc6c346181d1.png">
<img width="465" alt="screen shot 2018-07-15 at 12 24 05" src="https://user-images.githubusercontent.com/4459551/42732948-c458648c-882a-11e8-8b63-c60f4ce90e27.png">

I am running mysql server version 5.7 with http://npmjs.com/package/mysql npm package

**Comment by koskimas** [comment]
You are probably right. I'll fix this in `db-errors` library.

**Comment by koskimas** [comment]
This is now fixed in db-errors lib. `npm install` should select the new version.
