### ISSUE TITLE
`upsertGraph` and `insertGraph` errors.

### ISSUE THREAD

**Issue by ozum** [Vincit/objection-db-errors#4]
Hi,

Using `objection-db-errors`, I handle db errors on a central function.

When using `upsertGraph`, I may get errors like following

`Error: root model (id=12) does not exist. If you want to insert it with an id, use the insertMissing option`

It is not a db driver error, and `objection-db-errors` handles driver errors, but I think `objection-db-errors` should probably handle it, because it is actually a db error, not different from for example `NotFoundError`.

Could you please advise?

Kind regards,

**Comment by koskimas** [comment]
I don't think this library should handle that It's not actually a db error because it is thrown from javascript and not from db driver. This library is simply an objection wrapper for `db-errors` library and nothing more.

**Comment by koskimas** [comment]
Yes there is. See the error handing recipe in objection docs.

**Comment by koskimas** [comment]
http://vincit.github.io/objection.js/#error-handling

**Comment by koskimas** [comment]
Although it seems odd that you handle that error in your code. Seems like a programming error.

**Comment by ozum** [comment]
> http://vincit.github.io/objection.js/#error-handling

I already implemented it, and came here from there. My question is specific to error below:

`Error: root model (id=12) does not exist. If you want to insert it with an id, use the insertMissing option`

> Although it seems odd that you handle that error in your code. Seems like a programming error.

User executed a `PUT` query, but record does not exist. Objection throws error above. I want to return `404`.

```
PUT /item

{
  "id": 4
  "name": "some-name"
  "someGraph": {
    "id": 3,
    "color": "red"
  }
}
```

Current implementation:

```js
...
else if (error instanceof ConstraintViolationError) {
  return Boom.badRequest("Constraint error.");
} else if (typeof error.message === "string" && error.message.includes("use the insertMissing option")) {
  // For `upsertGraph`s "root model (id=...) does not exist..."" error
  return Boom.notFound("Not found");
}
```

**Comment by koskimas** [comment]
Seems to be related to this issue https://github.com/Vincit/objection.js/issues/1019
