### ISSUE TITLE
Typescript support please

### ISSUE THREAD

**Issue by skatpgusskat** [Vincit/objection-db-errors#5]
Hello.
I'm a big fan of objection.js
I trying to use objection-db-errors, but there is problem with typescript.

When I extends Objection.js Model with DbErrors in typescript, they cannot get Model's method like `query()`. 

Could you please support Typescript?

**Comment by koskimas** [comment]
I'd definitely merge a PR for typings.

**Comment by koskimas** [comment]
Actually the PR should be addressed to the `db-errors` library, which contains the error classes. This library is just a few lines of code to turn that library into an objection plugin.

**Comment by koskimas** [comment]
1.1.0 has been released with typings.
