### ISSUE TITLE
npm install @types/objection-db-errors not found 

### ISSUE THREAD

**Issue by androidTrainner** [Vincit/objection-db-errors#7]
In typescripts project, i am getting a continuous below ts lint warning 
`Could not find a declaration file for module 'objection-db-errors'. '{#projectPath}/node_modules/objection-db-errors/index.js' implicitly has an 'any' type.
  Try `npm install @types/objection-db-errors` if it exists or add a new declaration (.d.ts) file containing `declare module 'objection-db-errors';`ts(7016)`.

**This warning** suggest that it can be fixed using `npm install @types/objection-db-errors` but when i run npm install, it fail to find desired dependency and throw below error on cmd 

> npm ERR! code E404
npm ERR! 404 Not Found: @types/objection-db-errors@latest
npm ERR! A complete log of this run can be found in:

Any suggestions?

**Comment by koskimas** [comment]
There are no typings for this library yet. I don't no why you get that error though, but it cannot have anything to do with this library. The typings are on their way: #6

**Comment by androidTrainner** [comment]
Thanks koskimas. That means we need to spare this error till the next release of this library?

**Comment by koskimas** [comment]
A bunch of people are using this library with typescript without typings. That error is somehow caused by your setup.
