### ISSUE TITLE
Typescript definition seems wrong

### ISSUE THREAD

**Issue by abarre** [Vincit/objection-db-errors#8]
I suspect that the typescript definition is wrong. I am not a typescript expert, so I may have miss something.

I would have write : 
```typescript 
export function DBErrors<M extends Model>(modelClass: M): M
```
@petrhanak, could you provide an example for typescript ?

I tried different thing without success : 
```typescript
import { Model } from 'objection';
import { DBErrors } from 'objection-db-errors';

class ArticleBaseEntity extends Model {
//...
}
// compilation error : Argument of type 'typeof ArticleBaseEntity' is not assignable to parameter of type 'Model'.
//  Type 'typeof ArticleBaseEntity' is missing the following properties from type 'Model': $id, $beforeValidate, $validate, $afterValidate, and 28 more.
export default class ArticleEntity extends DBErrors(ArticleBaseEntity) {} 
```

**Comment by koskimas** [comment]
I think it should be something like
```js
export function DBErrors<M extends typeof Model>(modelClass: M): M
```
Could you try that out?

**Comment by koskimas** [comment]
Oh, it is like that. What you suggested is wrong. `M extends Model` is a type of model **instances**. Maybe the problem is that `extends` doesn't work like you'd expect here. Could something like `typeof M extends Model` work here?

**Comment by koskimas** [comment]
Or this

```ts
import { ModelClass } from 'objection'

export function DBErrors<M extends Model>(modelClass: ModelClass<M>): ModelClass<M>
```

**Comment by abarre** [comment]
Hi,
I tried again with the first definition and now it compiles. I am not sure of what was wrong the first time.
Thank you for the time you spent on this issue.
